---
- name: Write client list to temp file for comparison with existing certs
  copy:
    content: "{{ clients | join('\n') }}"
    dest: /tmp/client-list
    mode: "0644"
  when: openvpn_sync_certs

- name: Get existing certs
  shell: |
    set -o pipefail
    ls {{ openvpn_key_dir }} | grep '\.csr' | grep -v 'server.csr' | sort | cut -f1 -d'.' > /tmp/existing-certs
  args:
    executable: /bin/bash
  when: openvpn_sync_certs

- name: Get difference between 'clients' variable and existing certs
  shell: |
      set -o pipefail
      sort -o /tmp/client-list /tmp/client-list
      diff /tmp/client-list /tmp/existing-certs | grep '>' | awk '{print $2}'
  args:
    executable: /bin/bash
  register: _additional_certs_to_revoke
  when: openvpn_sync_certs

- name: Find clients to add and notify
  shell: |
      set -o pipefail
      sort -o /tmp/client-list /tmp/client-list
      diff /tmp/client-list /tmp/existing-certs | grep '<' | awk '{print $2}'
  args:
    executable: /bin/bash
  register: _additional_certs_to_add
  when: openvpn_sync_certs
