    - name: generate userhash for user
      shell: head -10 /dev/urandom | sha256sum | cut -b 1-30
      register: userhash

    - name: generate secret for mfa authenticator
      shell: oathtool --totp -v "{{ userhash.stdout }}" | grep Base32 | awk '{print $3}'
      register: oathsecret_base32 

    - debug:
        msg: "Send this to the user {{ client_username }}: {{ oathsecret_base32.stdout }}"

    - name: create new var
      set_fact:
        mfa_new_users_map: '{{ mfa_new_users_map | default([]) + [{"username": client_username, "secret": userhash.stdout }] }}'
