---
# Install the EPEL repo RPM on RedHat-like machines
# https://docs.fedoraproject.org/en-US/epel/getting-started/
# Thankfully openvpn is available in the base EPEL repo and
# I don't appear to have to worry about CRB/powertools/other repos
# https://wiki.almalinux.org/repos/AlmaLinux.html#almalinux-repositories
# https://wiki.rockylinux.org/rocky/repo/#base-repositories
# Also ignoring the request to install epel-next on CentOS Stream
# because that's only requested for CentOS Stream 9
- name: install | Install EPEL for CentOS & other RHEL clones
  ansible.builtin.package:
    name: "{{ epel_package_name }}"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution !="RedHat"

# EPEL install is different for RHEL specifically: https://www.redhat.com/en/blog/install-epel-linux
- name: install | Install EPEL for RHEL
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: true
  when: ansible_distribution == "RedHat"

- name: install | Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_pkg_mgr == "apt"

- name: install | Install openvpn
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ openvpn_package_name }}"
    - "{{ openssl_package_name }}"

# Use the built version:
# Fedora/EPEL: https://packages.fedoraproject.org/pkgs/openvpn-auth-ldap/openvpn-auth-ldap/index.html
# Debian: https://packages.debian.org/search?keywords=openvpn-auth-ldap
# Ubuntu: https://launchpad.net/ubuntu/+source/openvpn-auth-ldap
- name: install | Install LDAP plugin
  ansible.builtin.package:
    name: "{{ openvpn_ldap_plugin_package_name }}"
    state: present
  when:
    - openvpn_use_ldap is truthy
    - openvpn_use_prebuilt_ldap_plugin is truthy

# RHEL has the group 'nobody', 'Debian/Ubuntu' have 'nogroup'
# standardize on 'nogroup'
- name: install | Ensure group 'nogroup' is present
  ansible.builtin.group:
    name: nogroup
    state: present
    system: true
