---
- name: revocation | Remove client config
  ansible.builtin.file:
    path: "{{ openvpn_ovpn_dir }}/{{ item }}-{{ inventory_hostname }}.ovpn"
    state: absent
    force: true
  with_items:
    - "{{ openvpn_revoke_these_certs }}"
    - "{{ openvpn_cert_sync_revoke | default([]) }}"

- name: revocation | Revoke certificates
  ansible.builtin.command: sh revoke.sh {{ item }}.crt
  changed_when: true
  args:
    chdir: "{{ openvpn_key_dir }}"
  with_items:
    - "{{ openvpn_revoke_these_certs }}"
    - "{{ openvpn_cert_sync_revoke | default([]) }}"

- name: revocation | Remove client key
  ansible.builtin.file:
    path: "{{ openvpn_key_dir }}/{{ item }}.key"
    state: absent
    force: true
  with_items:
    - "{{ openvpn_revoke_these_certs }}"
    - "{{ openvpn_cert_sync_revoke | default([]) }}"

- name: revocation | Remove client csr
  ansible.builtin.file:
    path: "{{ openvpn_key_dir }}/{{ item }}.csr"
    state: absent
    force: true
  with_items:
    - "{{ openvpn_revoke_these_certs }}"
    - "{{ openvpn_cert_sync_revoke | default([]) }}"

- name: revocation | Remove client cert
  ansible.builtin.file:
    path: "{{ openvpn_key_dir }}/{{ item }}.crt"
    state: absent
    force: true
  with_items:
    - "{{ openvpn_revoke_these_certs }}"
    - "{{ openvpn_cert_sync_revoke | default([]) }}"
