- name: Start ufw service
  service:
    name: ufw
    enabled: true
    state: started

- name: Enable ufw
  ufw:
    state: enabled
    policy: allow

- name: ufw - enable forwarding
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: DEFAULT_FORWARD_POLICY="ACCEPT"

- name: ufw - Allow incoming VPN connection
  ufw:
    direction: in
    proto: "{{openvpn_proto}}"
    to_port: "{{openvpn_port}}"
    rule: allow

- name: ufw - Accept packets from VPN tunnel adaptor
  ufw:
    direction: in
    interface: tun0
    rule: allow

- name: ufw - template rules.before
  template:
    src: before.rules.j2
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ufw

- pause:
    seconds: 5