---
- name: uninstall | Disable openvpn auto-start & start
  ansible.builtin.service:
    name: "{{ openvpn_service_name }}"
    enabled: false
    state: stopped

- name: uninstall | Wipe out config directory
  ansible.builtin.file:
    path: "{{ openvpn_base_dir }}"
    state: absent

- name: uninstall | Remove openvpn logrotate config file
  ansible.builtin.file:
    path: /etc/logrotate.d/openvpn.conf
    state: absent

- name: uninstall | Uninstall OpenVPN
  ansible.builtin.package:
    name: "{{ openvpn_package_name }}"
    state: absent

- name: uninstall | Uninstall LDAP plugin
  ansible.builtin.package:
    name: "{{ openvpn_ldap_plugin_package_name }}"
    state: absent
  when: openvpn_use_ldap is truthy

- name: uninstall | Terminate playbook
  ansible.builtin.meta: end_host
