---
- name: Restart openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service_name }}"
    state: restarted
  # Github Actions doesn't allow entrypoints, so PID 1 isn't an init system
  when: ansible_service_mgr != "tail"

- name: Restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: Save iptables rules (Debian/Ubuntu and CentOS/RHEL/Fedora)
  ansible.builtin.shell: "{{ iptables_save_command }}" # noqa command-instead-of-shell could have shell redirection
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
  listen: "Save iptables"
  changed_when: true # always save iptables rules
