name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    name: fedora-${{ matrix.version }}
    strategy:
      matrix:
        version: ["32", "33", "34"]
           
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run docker container
        run: sudo docker run --detach -e "container=docker"  -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun --volume="${GITHUB_WORKSPACE}":/etc/ansible/roles/ansible-role-openvpn:ro --name fedora /usr/lib/systemd/systemd --system
      - name: Make sure ansible connection is sane
        run: sudo docker exec fedora ansible -m setup -c local -i 127.0.0.1, all
      - name: Check syntax of ansible playbook
        run: sudo docker exec fedora ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml --syntax-check
      - name: Run ansible playbook
        run: sudo docker exec fedora ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
      - name: Check idempotency
        run: sudo docker exec fedora ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
