name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    name: fedora-${{ matrix.version }}
    strategy:
      matrix:
        version: ["32", "33", "34"]
    container: 
      image: diodonfrost/ansible-fedora:${{ matrix.version }}
      volumes: 
          - /sys/fs/cgroup:/sys/fs/cgroup
          - ${{GITHUB_WORKSPACE}}:/etc/ansible/roles/ansible-role-openvpn
      options: "--cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun"
      env:
        container: "docker"
           
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make sure ansible connection is sane
        run: ansible -m setup -c local -i 127.0.0.1, all
