name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    name: check-syntax
    container: 
      image: diodonfrost/ansible-fedora:34
      env:
        container: docker
      volumes: 
        - /sys/fs/cgroup:/sys/fs/cgroup
        - ${{ github.workspace }}:/etc/ansible/roles/ansible-role-openvpn
      options: "--cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check syntax of ansible playbook
        run: ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml --syntax-check
      
  build-fedora:
    runs-on: ubuntu-latest
    name: fedora-${{ matrix.version }}
    needs: [check-syntax]
    strategy:
       fail-fast: false
       matrix:
        version: ["32", "33", "34"]
           
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create docker container
        run: docker create --name fedora --cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun --entrypoint /usr/sbin/init -e "container=docker" -e CI=true -v "/sys/fs/cgroup":"/sys/fs/cgroup" -v ${{ github.workspace }}:/etc/ansible/roles/ansible-role-openvpn diodonfrost/ansible-fedora:${{ matrix.version }}
      - run: docker start fedora
      - run: |
          docker ps
          sleep 3
          docker ps
      - name: Make sure ansible connection is sane
        run: docker exec fedora ansible -m setup -c local -i 127.0.0.1, all
      - name: Run ansible playbook
        run: docker exec fedora ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
        continue-on-error: true
      - run: docker exec fedora ls -lR /etc/openvpn
      - name: Check idempotency
        run: docker exec fedora ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
      - run: cat /var/log/openvpn.log
      - run: ls -r /etc/openvpn
      - run: cat /etc/openvpn/openvpn_udp_1194.conf
      - run: cat /etc/openvpn/alpha-127.0.0.1.ovpn
